In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
print(x_data.shape)  # torch.Size([2, 2])

torch.Size([2, 2])


In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np.shape)  # torch.Size([2, 2])

torch.Size([2, 2])


In [8]:
x_ones = torch.ones_like(x_data)
print(x_ones)  # tensor([[1, 1], [1, 1]])

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)  # tensor([[0.1234, 0.5678], [0.9101, 0.1121]])


tensor([[1, 1],
        [1, 1]])
tensor([[0.0114, 0.9747],
        [0.8095, 0.9563]])


In [11]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)  # tensor([[0.1234, 0.5678, 0.9101], [0.1121, 0.3141, 0.5161]])
print(ones_tensor)  # tensor([[1., 1., 1.], [1., 1., 1.]])
print(zeros_tensor)  # tensor([[0., 0., 0.], [0., 0., 0.]])

tensor([[0.8343, 0.2119, 0.6700],
        [0.0317, 0.9333, 0.9871]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
tensor = torch.rand(3,4)
print(tensor)  # tensor([[0.1234, 0.5678, 0.9101, 0.1121], [0.3141, 0.5161, 0.7182, 0.9202], [0.1223, 0.3245, 0.5267, 0.7289]])
print(tensor.dtype)
tensor = tensor.to('cuda')
print(tensor.device)  # device(type='cuda')
print(tensor.shape)

tensor([[0.7998, 0.8996, 0.6762, 0.2695],
        [0.1270, 0.6604, 0.3976, 0.8656],
        [0.4138, 0.4754, 0.2312, 0.6364]])
torch.float32
cuda:0
torch.Size([3, 4])


In [15]:
if torch.accelerator.is_available():
    print("CUDA is available")
    tensor = tensor.to(torch.accelerator.current_accelerator())

CUDA is available


In [23]:
tensor = torch.ones(4, 4)
print(tensor)
print(tensor[0])
print(tensor[:, 1])
print(tensor[1, :])
tensor[:,1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [26]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)#按列拼接
print(t1.shape)  # torch.Size([4, 12])
print(t1)

torch.Size([4, 12])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [28]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor, out=z3)
print("y1",y1)
print("y2",y2)
print("y3",y3)
print("z1",z1)
print("z2",z2)
print("z3",z3)

y1 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z1 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [29]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item))  # 16.0 <class 'float'>
print(tensor)

12.0 <class 'float'>
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [30]:
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Bridge with Numpy

### Tensor to NumPy array

In [32]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)  # [1. 1. 1. 1. 1.]
t.add_(1)
print(t)  # tensor([2., 2., 2., 2., 2.])

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])


### NumPy array to Tensor

In [34]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [35]:
np.add(n, 1, out=n)
print(n)  # [2. 2. 2. 2. 2.]

[2. 2. 2. 2. 2.]
